import React from 'react';
import styles from './index.css';
import {DateTime} from '../date-time';
import {String} from '../string';
import classNames from 'classnames';

export class Autogenerated extends React.Component{

  renderData() {
    if(this.props.columnValue.dataType.subType === "Date Created"
      || this.props.columnValue.dataType.subType === "Date Last Amended") {
      return <DateTime {...this.props} />;
    }
    else {
      return <String {...this.props} />;
    }
  }

  formatDate() {
    const date = new Date(this.props.columnValue.value);
      if(this.props.columnValue.value == null){
        return '';
      }
      else
        return date.getDate()+"/"+(date.getMonth() + 1).toString()+"/"+date.getFullYear()+
          " "+date.getHours()+":"+date.getMinutes()+":"+date.getSeconds();
  }

  renderInput() {
    const classes = classNames(this.props.className, styles.input);
    if(this.props.columnValue.filterable) {
      return <input className={classes} value={this.props.columnValue.value} onChange={(e) => this.props.onChange(e.target.value)}/>;
    }
    if(this.props.columnValue.dataType.subType === "Date Created"
      || this.props.columnValue.dataType.subType === "Date Last Amended") {
    return <input className={classes} disabled value={this.formatDate()}/>;
    }
    else
    {
     return <input disabled className={classes} value={this.props.columnValue.value || 'System generated'} />;
    }
  }

  render() {
    return <span>{this.props.columnValue.editable? this.renderInput() : this.renderData() }</span>;
  }
}
