//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace TE.ComponentLibrary.ComponentLibrary.ServiceSAPServiceReference {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ServiceMaster_OutBinding", Namespace="http://total-environment/PI/ServiceMaster")]
    public partial class ServiceMaster_OutService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ServiceMaster_OutOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ServiceMaster_OutService() {
            this.Url = global::TE.ComponentLibrary.ComponentLibrary.Properties.Settings.Default.ComponentLibrary_ServiceSAPServiceReference_ServiceMaster_OutService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ServiceMaster_OutCompletedEventHandler ServiceMaster_OutCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://sap.com/xi/WebService/soap1.1", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlArrayAttribute("ServiceMasterRes", Namespace="http://total-environment/PI/ServiceMaster")]
        [return: System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ServiceMasterResItem[] ServiceMaster_Out([System.Xml.Serialization.XmlElementAttribute(Namespace="http://total-environment/PI/ServiceMaster")] ServiceMasterReq ServiceMasterReq) {
            object[] results = this.Invoke("ServiceMaster_Out", new object[] {
                        ServiceMasterReq});
            return ((ServiceMasterResItem[])(results[0]));
        }
        
        /// <remarks/>
        public void ServiceMaster_OutAsync(ServiceMasterReq ServiceMasterReq) {
            this.ServiceMaster_OutAsync(ServiceMasterReq, null);
        }
        
        /// <remarks/>
        public void ServiceMaster_OutAsync(ServiceMasterReq ServiceMasterReq, object userState) {
            if ((this.ServiceMaster_OutOperationCompleted == null)) {
                this.ServiceMaster_OutOperationCompleted = new System.Threading.SendOrPostCallback(this.OnServiceMaster_OutOperationCompleted);
            }
            this.InvokeAsync("ServiceMaster_Out", new object[] {
                        ServiceMasterReq}, this.ServiceMaster_OutOperationCompleted, userState);
        }
        
        private void OnServiceMaster_OutOperationCompleted(object arg) {
            if ((this.ServiceMaster_OutCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ServiceMaster_OutCompleted(this, new ServiceMaster_OutCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://total-environment/PI/ServiceMaster")]
    public partial class ServiceMasterReq {
        
        private ServiceMasterReqItem[] itemField;
        
        private ServiceMasterReqItem1[] item1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ServiceMasterReqItem[] item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("item1", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ServiceMasterReqItem1[] item1 {
            get {
                return this.item1Field;
            }
            set {
                this.item1Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://total-environment/PI/ServiceMaster")]
    public partial class ServiceMasterReqItem {
        
        private string sERVICENUMBERField;
        
        private string mATL_GROUPField;
        
        private string bASE_UOMField;
        
        private string sERV_CATField;
        
        private string p_STATUSField;
        
        private string vALID_FROMField;
        
        private string vAL_CLASSField;
        
        private string sERV_TYPEField;
        
        private string sHORT_TEXTField;
        
        private string cHANGE_IDField;
        
        private string eAN11Field;
        
        private string uSERF1_TXTField;
        
        private string tAXTARIFFCODEField;
        
        private string tAXIMField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SERVICENUMBER {
            get {
                return this.sERVICENUMBERField;
            }
            set {
                this.sERVICENUMBERField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MATL_GROUP {
            get {
                return this.mATL_GROUPField;
            }
            set {
                this.mATL_GROUPField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BASE_UOM {
            get {
                return this.bASE_UOMField;
            }
            set {
                this.bASE_UOMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SERV_CAT {
            get {
                return this.sERV_CATField;
            }
            set {
                this.sERV_CATField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string P_STATUS {
            get {
                return this.p_STATUSField;
            }
            set {
                this.p_STATUSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string VALID_FROM {
            get {
                return this.vALID_FROMField;
            }
            set {
                this.vALID_FROMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string VAL_CLASS {
            get {
                return this.vAL_CLASSField;
            }
            set {
                this.vAL_CLASSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SERV_TYPE {
            get {
                return this.sERV_TYPEField;
            }
            set {
                this.sERV_TYPEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SHORT_TEXT {
            get {
                return this.sHORT_TEXTField;
            }
            set {
                this.sHORT_TEXTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CHANGE_ID {
            get {
                return this.cHANGE_IDField;
            }
            set {
                this.cHANGE_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string EAN11 {
            get {
                return this.eAN11Field;
            }
            set {
                this.eAN11Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string USERF1_TXT {
            get {
                return this.uSERF1_TXTField;
            }
            set {
                this.uSERF1_TXTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TAXTARIFFCODE {
            get {
                return this.tAXTARIFFCODEField;
            }
            set {
                this.tAXTARIFFCODEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TAXIM {
            get {
                return this.tAXIMField;
            }
            set {
                this.tAXIMField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://total-environment/PI/ServiceMaster")]
    public partial class ServiceMasterReqItem1 {
        
        private string tDLINEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TDLINE {
            get {
                return this.tDLINEField;
            }
            set {
                this.tDLINEField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://total-environment/PI/ServiceMaster")]
    public partial class ServiceMasterResItem {
        
        private string aSNUMField;
        
        private string eAN11Field;
        
        private string uSERF1_TXTField;
        
        private string rETCODEField;
        
        private string mESSAGEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ASNUM {
            get {
                return this.aSNUMField;
            }
            set {
                this.aSNUMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string EAN11 {
            get {
                return this.eAN11Field;
            }
            set {
                this.eAN11Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string USERF1_TXT {
            get {
                return this.uSERF1_TXTField;
            }
            set {
                this.uSERF1_TXTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string RETCODE {
            get {
                return this.rETCODEField;
            }
            set {
                this.rETCODEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MESSAGE {
            get {
                return this.mESSAGEField;
            }
            set {
                this.mESSAGEField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void ServiceMaster_OutCompletedEventHandler(object sender, ServiceMaster_OutCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ServiceMaster_OutCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ServiceMaster_OutCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ServiceMasterResItem[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ServiceMasterResItem[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591