import React from 'react';
import {shallow} from 'enzyme';
import sinonChai from 'sinon-chai';
import chai, {expect} from 'chai';
import chaiEnzyme from 'chai-enzyme';
import sinon from 'sinon';

import {PageTab} from '../../src/components/page-tab'

chai.use(sinonChai);
chai.use(chaiEnzyme());

describe("Page Tab with material data", () => {
  let props, wrapper, onCurrentHeaderChange;
  beforeEach(() => {
    onCurrentHeaderChange = sinon.spy();
    props = {
      onSort: sinon.spy(),
      componentType: "material",
      values: [
        {
          "headers": [
            {
              "columns": [
                {
                  "dataType": {
                    "name": "Constant",
                    "subType": "Primary"
                  },
                  "key": "material_level_1",
                  "name": "Material Level 1",
                  "value": "Primary"
                },
                {
                  "dataType": {
                    "name": "Constant",
                    "subType": "Aluminium and Copper"
                  },
                  "key": "material_level_2",
                  "name": "Material Level 2",
                  "value": "Aluminium and Copper"
                },
                {
                  "dataType": {
                    "name": "MasterData",
                    "subType": "590c5a93c40d554e2c3c53e1"
                  },
                  "key": "material_level_3",
                  "name": "Material Level 3",
                  "value": "Copper"
                },
                {
                  "dataType": {
                    "name": "MasterData",
                    "subType": "590c5a93c40d554e2c3c53e2"
                  },
                  "key": "material_level_4",
                  "name": "Material Level 4",
                  "value": "Copper Sheet"
                },
                {
                  "dataType": {
                    "name": "MasterData",
                    "subType": "590c5a93c40d554e2c3c53e3"
                  },
                  "key": "material_level_5",
                  "name": "Material Level 5",
                  "value": null
                },
                {
                  "dataType": {
                    "name": "MasterData",
                    "subType": "590c5a93c40d554e2c3c53e4"
                  },
                  "key": "material_level_6",
                  "name": "Material Level 6",
                  "value": null
                },
                {
                  "dataType": {
                    "name": "MasterData",
                    "subType": "590c5a93c40d554e2c3c53e5"
                  },
                  "key": "material_level_7",
                  "name": "Material Level 7",
                  "value": null
                }
              ],
              "key": "classification",
              "name": "Classification"
            },
            {
              "columns": [
                {
                  "dataType": {
                    "name": "String",
                    "subType": null
                  },
                  "key": "material_name",
                  "name": "Material Name",
                  "value": null
                },
                {
                  "dataType": {
                    "name": "Autogenerated",
                    "subType": "Material Code"
                  },
                  "key": "material_code",
                  "name": "Material Code",
                  "value": "ALM000048"
                },
                {
                  "dataType": {
                    "name": "Array",
                    "subType": {
                      "name": "StaticFile",
                      "subType": null
                    }
                  },
                  "key": "image",
                  "name": "Image",
                  "value": [
                    {
                      "url": "http://127.0.0.1:10000/devstoreaccount1/static-files/fded40a9-cc4f-4f77-ac1c-b4a2814a1e8a.jpg",
                      "name": "fded40a9-cc4f-4f77-ac1c-b4a2814a1e8a.jpg",
                      "id": "652cecff7f3241c291008ab6cf11f519"
                    }
                  ]
                },
                {
                  "dataType": {
                    "name": "String",
                    "subType": null
                  },
                  "key": "short_description",
                  "name": "Short Description",
                  "value": null
                },
                {
                  "dataType": {
                    "name": "String",
                    "subType": null
                  },
                  "key": "shade_number",
                  "name": "Shade Number",
                  "value": null
                },
                {
                  "dataType": {
                    "name": "String",
                    "subType": null
                  },
                  "key": "shade_description",
                  "name": "Shade Description",
                  "value": null
                },
                {
                  "dataType": {
                    "name": "String",
                    "subType": null
                  },
                  "key": "unit_of_measure",
                  "name": "Unit Of Measure",
                  "value": null
                },
                {
                  "dataType": {
                    "name": "String",
                    "subType": null
                  },
                  "key": "hsn_code",
                  "name": "HSN Code",
                  "value": null
                },
                {
                  "dataType": {
                    "name": "String",
                    "subType": null
                  },
                  "key": "sap_code",
                  "name": "SAP Code",
                  "value": null
                },
                {
                  "dataType": {
                    "name": "Boolean",
                    "subType": null
                  },
                  "key": "part_of_ebuild_library",
                  "name": "Part of eBuild Library",
                  "value": null
                },
                {
                  "dataType": {
                    "name": "Boolean",
                    "subType": null
                  },
                  "key": "generic",
                  "name": "Generic",
                  "value": null
                },
                {
                  "dataType": {
                    "name": "Boolean",
                    "subType": null
                  },
                  "key": "manufactured",
                  "name": "Manufactured",
                  "value": null
                },
                {
                  "dataType": {
                    "name": "MasterData",
                    "subType": "590c5a94c40d554e2c3c53fb"
                  },
                  "key": "material_status",
                  "name": "Material Status",
                  "value": null
                }
              ],
              "key": "general",
              "name": "General"
            },
            {
              "columns": [
                {
                  "dataType": {
                    "name": "StaticFile",
                    "subType": null
                  },
                  "key": "quantity_evaluation_method",
                  "name": "Quantity Evaluation Method",
                  "value": {
                    "url": "http://127.0.0.1:10000/devstoreaccount1/static-files/8670cf0b-df5d-410e-99ad-5fb73662f4b2.pdf",
                    "name": "8670cf0b-df5d-410e-99ad-5fb73662f4b2.pdf",
                    "id": "7de3a034f4f94a99b26e2af81e63435c"
                  }
                },
                {
                  "dataType": {
                    "name": "CheckList",
                    "subType": null
                  },
                  "key": "general_po_terms_&_conditions",
                  "name": "General PO Terms & Conditions",
                  "value": null
                },
                {
                  "dataType": {
                    "name": "CheckList",
                    "subType": null
                  },
                  "key": "special_po_terms_&_conditions",
                  "name": "Special PO Terms & Conditions",
                  "value": null
                },
                {
                  "dataType": {
                    "name": "Money",
                    "subType": null
                  },
                  "key": "last_purchase_rate",
                  "name": "Last Purchase Rate",
                  "value": null
                },
                {
                  "dataType": {
                    "name": "Money",
                    "subType": null
                  },
                  "key": "weighted_average_purchase_rate",
                  "name": "Weighted Average Purchase Rate",
                  "value": null
                },
                {
                  "dataType": {
                    "name": "Unit",
                    "subType": "%"
                  },
                  "key": "procurement_rate_threshold_%",
                  "name": "Procurement Rate Threshold %",
                  "value": null
                },
                {
                  "dataType": {
                    "name": "Array",
                    "subType": {
                      "name": "Brand",
                      "subType": "BAC"
                    }
                  },
                  "key": "approved_brands",
                  "name": "Associated Brands",
                  "value": [
                    {
                      "columns": [
                        {
                          "dataType": {
                            "name": "Autogenerated",
                            "subType": "Brand Code"
                          },
                          "key": "brand_code",
                          "name": "Brand Code",
                          "value": "BAC0001"
                        },
                        {
                          "dataType": {
                            "name": "String",
                            "subType": null
                          },
                          "key": "manufacturer's_name",
                          "name": "Manufacturer's Name",
                          "value": "te"
                        },
                        {
                          "dataType": {
                            "name": "String",
                            "subType": null
                          },
                          "key": "brand/series",
                          "name": "Brand/Series",
                          "value": "12"
                        },
                        {
                          "dataType": {
                            "name": "String",
                            "subType": null
                          },
                          "key": "manufacturer's_code",
                          "name": "Manufacturer's Code",
                          "value": "12344"
                        },
                        {
                          "dataType": {
                            "name": "StaticFile",
                            "subType": null
                          },
                          "key": "manufacturer's_specification",
                          "name": "Manufacturer's Specification",
                          "value": null
                        },
                        {
                          "dataType": {
                            "name": "StaticFile",
                            "subType": null
                          },
                          "key": "material_safety_data_sheet",
                          "name": "Material Safety Data Sheet",
                          "value": null
                        },
                        {
                          "dataType": {
                            "name": "StaticFile",
                            "subType": null
                          },
                          "key": "technical_drawing",
                          "name": "Technical Drawing",
                          "value": null
                        },
                        {
                          "dataType": {
                            "name": "StaticFile",
                            "subType": null
                          },
                          "key": "3d_model",
                          "name": "3D Model",
                          "value": null
                        },
                        {
                          "dataType": {
                            "name": "MasterData",
                            "subType": "590c5a94c40d554e2c3c53fc"
                          },
                          "key": "country_of_manufacture",
                          "name": "Country of Manufacture",
                          "value": "India"
                        },
                        {
                          "dataType": {
                            "name": "Int",
                            "subType": null
                          },
                          "key": "warranty_period_in_years",
                          "name": "Warranty Period in Years",
                          "value": 10
                        },
                        {
                          "dataType": {
                            "name": "MasterData",
                            "subType": "590c5a94c40d554e2c3c53fb"
                          },
                          "key": "status",
                          "name": "Status",
                          "value": "Approved"
                        },
                        {
                          "dataType": {
                            "name": "String",
                            "subType": null
                          },
                          "key": "approved_vendors",
                          "name": "Approved Vendors",
                          "value": "123"
                        },
                        {
                          "dataType": {
                            "name": "Int",
                            "subType": null
                          },
                          "key": "shelf_life_in_days",
                          "name": "Shelf Life in Days",
                          "value": 223
                        },
                        {
                          "dataType": {
                            "name": "String",
                            "subType": null
                          },
                          "key": "packing_list",
                          "name": "Packing List",
                          "value": "fjdf"
                        }
                      ]
                    }
                  ]
                },
                {
                  "dataType": {
                    "name": "Array",
                    "subType": {
                      "name": "String",
                      "subType": null
                    }
                  },
                  "key": "approved_vendors",
                  "name": "Approved Vendors",
                  "value": null
                }
              ],
              "key": "purchase",
              "name": "Purchase"
            },
            {
              "columns": [
                {
                  "dataType": {
                    "name": "Int",
                    "subType": null
                  },
                  "key": "po_lead_time_in_days",
                  "name": "PO Lead Time in Days",
                  "value": null
                },
                {
                  "dataType": {
                    "name": "Int",
                    "subType": null
                  },
                  "key": "delivery_lead_time_in_days",
                  "name": "Delivery Lead Time in Days",
                  "value": null
                },
                {
                  "dataType": {
                    "name": "Int",
                    "subType": null
                  },
                  "key": "minimum_order_quantity",
                  "name": "Minimum Order Quantity",
                  "value": null
                },
                {
                  "dataType": {
                    "name": "Boolean",
                    "subType": null
                  },
                  "key": "maintain_lot",
                  "name": "Maintain Lot",
                  "value": null
                }
              ],
              "key": "planning",
              "name": "Planning"
            },
            {
              "columns": [
                {
                  "dataType": {
                    "name": "String",
                    "subType": null
                  },
                  "key": "governing_standard",
                  "name": "Governing Standard",
                  "value": null
                },
                {
                  "dataType": {
                    "name": "StaticFile",
                    "subType": null
                  },
                  "key": "storage_method",
                  "name": "Storage Method",
                  "value": null
                },
                {
                  "dataType": {
                    "name": "CheckList",
                    "subType": null
                  },
                  "key": "inspection_checklist",
                  "name": "Inspection Checklist",
                  "value": null
                },
                {
                  "dataType": {
                    "name": "StaticFile",
                    "subType": null
                  },
                  "key": "sampling_method",
                  "name": "Sampling Method",
                  "value": null
                }
              ],
              "key": "quality",
              "name": "Quality"
            },
            {
              "columns": [
                {
                  "dataType": {
                    "name": "Autogenerated",
                    "subType": "Date Created"
                  },
                  "key": "date_created",
                  "name": "Date Created",
                  "value": "2017-06-23T06:50:41.788Z"
                },
                {
                  "dataType": {
                    "name": "Autogenerated",
                    "subType": "Created By"
                  },
                  "key": "created_by",
                  "name": "Created By",
                  "value": "TE"
                },
                {
                  "dataType": {
                    "name": "Autogenerated",
                    "subType": "Date Last Amended"
                  },
                  "key": "date_last_amended",
                  "name": "Date Last Amended",
                  "value": "2017-06-27T05:20:04.824Z"
                },
                {
                  "dataType": {
                    "name": "Autogenerated",
                    "subType": "Last Amended By"
                  },
                  "key": "last_amended_by",
                  "name": "Last Amended By",
                  "value": "TE"
                }
              ],
              "key": "system_logs",
              "name": "System Logs"
            },
            {
              "columns": [
                {
                  "dataType": {
                    "name": "CheckList",
                    "subType": null
                  },
                  "key": "specification_sheet",
                  "name": "Specification Sheet",
                  "value": null
                },
                {
                  "dataType": {
                    "name": "String",
                    "subType": null
                  },
                  "key": "grade",
                  "name": "Grade",
                  "value": null
                },
                {
                  "dataType": {
                    "name": "Unit",
                    "subType": "mm"
                  },
                  "key": "length",
                  "name": "Length",
                  "value": null
                },
                {
                  "dataType": {
                    "name": "Unit",
                    "subType": "mm"
                  },
                  "key": "width",
                  "name": "Width",
                  "value": null
                },
                {
                  "dataType": {
                    "name": "Unit",
                    "subType": "mm"
                  },
                  "key": "height",
                  "name": "Height",
                  "value": null
                },
                {
                  "dataType": {
                    "name": "Unit",
                    "subType": "mm"
                  },
                  "key": "thickness",
                  "name": "Thickness",
                  "value": null
                },
                {
                  "dataType": {
                    "name": "String",
                    "subType": null
                  },
                  "key": "method",
                  "name": "Method",
                  "value": null
                },
                {
                  "dataType": {
                    "name": "String",
                    "subType": null
                  },
                  "key": "temper_designation",
                  "name": "Temper Designation",
                  "value": null
                },
                {
                  "dataType": {
                    "name": "String",
                    "subType": null
                  },
                  "key": "finish",
                  "name": "Finish",
                  "value": null
                },
                {
                  "dataType": {
                    "name": "Unit",
                    "subType": "kg/m²"
                  },
                  "key": "weight/unit_area",
                  "name": "Weight/Unit Area",
                  "value": null
                },
                {
                  "dataType": {
                    "name": "Unit",
                    "subType": "kg/m"
                  },
                  "key": "weight/unit_length",
                  "name": "Weight/Unit Length",
                  "value": null
                },
                {
                  "dataType": {
                    "name": "String",
                    "subType": null
                  },
                  "key": "additional_features",
                  "name": "Additional Features",
                  "value": "nthg"
                }
              ],
              "key": "specifications",
              "name": "Specifications"
            }
          ],
          "group": "Aluminium and Copper",
          "id": "ALM000048"
        },
        {
          "headers": [
            {
              "columns": [
                {
                  "dataType": {
                    "name": "Constant",
                    "subType": "Primary"
                  },
                  "key": "material_level_1",
                  "name": "Material Level 1",
                  "value": "Primary"
                },
                {
                  "dataType": {
                    "name": "Constant",
                    "subType": "Aluminium and Copper"
                  },
                  "key": "material_level_2",
                  "name": "Material Level 2",
                  "value": "Aluminium and Copper"
                },
                {
                  "dataType": {
                    "name": "MasterData",
                    "subType": "590c5a93c40d554e2c3c53e1"
                  },
                  "key": "material_level_3",
                  "name": "Material Level 3",
                  "value": "Aluminium"
                },
                {
                  "dataType": {
                    "name": "MasterData",
                    "subType": "590c5a93c40d554e2c3c53e2"
                  },
                  "key": "material_level_4",
                  "name": "Material Level 4",
                  "value": "Aluminium Straight edge"
                },
                {
                  "dataType": {
                    "name": "MasterData",
                    "subType": "590c5a93c40d554e2c3c53e3"
                  },
                  "key": "material_level_5",
                  "name": "Material Level 5",
                  "value": null
                },
                {
                  "dataType": {
                    "name": "MasterData",
                    "subType": "590c5a93c40d554e2c3c53e4"
                  },
                  "key": "material_level_6",
                  "name": "Material Level 6",
                  "value": null
                },
                {
                  "dataType": {
                    "name": "MasterData",
                    "subType": "590c5a93c40d554e2c3c53e5"
                  },
                  "key": "material_level_7",
                  "name": "Material Level 7",
                  "value": null
                }
              ],
              "key": "classification",
              "name": "Classification"
            },
            {
              "columns": [
                {
                  "dataType": {
                    "name": "String",
                    "subType": null
                  },
                  "key": "material_name",
                  "name": "Material Name",
                  "value": "Aluminium Straight Edge"
                },
                {
                  "dataType": {
                    "name": "Autogenerated",
                    "subType": "Material Code"
                  },
                  "key": "material_code",
                  "name": "Material Code",
                  "value": "ALM000047"
                },
                {
                  "dataType": {
                    "name": "Array",
                    "subType": {
                      "name": "StaticFile",
                      "subType": null
                    }
                  },
                  "key": "image",
                  "name": "Image",
                  "value": [
                    {
                      "url": "http://127.0.0.1:10000/devstoreaccount1/static-files/fded40a9-cc4f-4f77-ac1c-b4a2814a1e8a.jpg",
                      "name": "fded40a9-cc4f-4f77-ac1c-b4a2814a1e8a.jpg",
                      "id": "652cecff7f3241c291008ab6cf11f519"
                    }
                  ]
                },
                {
                  "dataType": {
                    "name": "String",
                    "subType": null
                  },
                  "key": "short_description",
                  "name": "Short Description",
                  "value": "Aluminium Straight Edge"
                },
                {
                  "dataType": {
                    "name": "String",
                    "subType": null
                  },
                  "key": "shade_number",
                  "name": "Shade Number",
                  "value": "bhbh"
                },
                {
                  "dataType": {
                    "name": "String",
                    "subType": null
                  },
                  "key": "shade_description",
                  "name": "Shade Description",
                  "value": null
                },
                {
                  "dataType": {
                    "name": "String",
                    "subType": null
                  },
                  "key": "unit_of_measure",
                  "name": "Unit Of Measure",
                  "value": "Nos"
                },
                {
                  "dataType": {
                    "name": "String",
                    "subType": null
                  },
                  "key": "hsn_code",
                  "name": "HSN Code",
                  "value": null
                },
                {
                  "dataType": {
                    "name": "String",
                    "subType": null
                  },
                  "key": "sap_code",
                  "name": "SAP Code",
                  "value": "2000834"
                },
                {
                  "dataType": {
                    "name": "Boolean",
                    "subType": null
                  },
                  "key": "part_of_ebuild_library",
                  "name": "Part of eBuild Library",
                  "value": false
                },
                {
                  "dataType": {
                    "name": "Boolean",
                    "subType": null
                  },
                  "key": "generic",
                  "name": "Generic",
                  "value": true
                },
                {
                  "dataType": {
                    "name": "Boolean",
                    "subType": null
                  },
                  "key": "manufactured",
                  "name": "Manufactured",
                  "value": true
                },
                {
                  "dataType": {
                    "name": "MasterData",
                    "subType": "590c5a94c40d554e2c3c53fb"
                  },
                  "key": "material_status",
                  "name": "Material Status",
                  "value": "Under Development"
                }
              ],
              "key": "general",
              "name": "General"
            },
            {
              "columns": [
                {
                  "dataType": {
                    "name": "StaticFile",
                    "subType": null
                  },
                  "key": "quantity_evaluation_method",
                  "name": "Quantity Evaluation Method",
                  "value": {
                    "url": "http://127.0.0.1:10000/devstoreaccount1/static-files/8670cf0b-df5d-410e-99ad-5fb73662f4b2.pdf",
                    "name": "8670cf0b-df5d-410e-99ad-5fb73662f4b2.pdf",
                    "id": "7de3a034f4f94a99b26e2af81e63435c"
                  }
                },
                {
                  "dataType": {
                    "name": "CheckList",
                    "subType": null
                  },
                  "key": "general_po_terms_&_conditions",
                  "name": "General PO Terms & Conditions",
                  "value": null
                },
                {
                  "dataType": {
                    "name": "CheckList",
                    "subType": null
                  },
                  "key": "special_po_terms_&_conditions",
                  "name": "Special PO Terms & Conditions",
                  "value": null
                },
                {
                  "dataType": {
                    "name": "Money",
                    "subType": null
                  },
                  "key": "last_purchase_rate",
                  "name": "Last Purchase Rate",
                  "value": null
                },
                {
                  "dataType": {
                    "name": "Money",
                    "subType": null
                  },
                  "key": "weighted_average_purchase_rate",
                  "name": "Weighted Average Purchase Rate",
                  "value": null
                },
                {
                  "dataType": {
                    "name": "Unit",
                    "subType": "%"
                  },
                  "key": "procurement_rate_threshold_%",
                  "name": "Procurement Rate Threshold %",
                  "value": null
                },
                {
                  "dataType": {
                    "name": "Array",
                    "subType": {
                      "name": "Brand",
                      "subType": "BAC"
                    }
                  },
                  "key": "approved_brands",
                  "name": "Associated Brands",
                  "value": [
                    {
                      "columns": [
                        {
                          "dataType": {
                            "name": "Autogenerated",
                            "subType": "Brand Code"
                          },
                          "key": "brand_code",
                          "name": "Brand Code",
                          "value": "BAC0002"
                        },
                        {
                          "dataType": {
                            "name": "String",
                            "subType": null
                          },
                          "key": "manufacturer's_name",
                          "name": "Manufacturer's Name",
                          "value": "dsjjdsjncd"
                        },
                        {
                          "dataType": {
                            "name": "String",
                            "subType": null
                          },
                          "key": "brand/series",
                          "name": "Brand/Series",
                          "value": "JSFKJ"
                        },
                        {
                          "dataType": {
                            "name": "String",
                            "subType": null
                          },
                          "key": "manufacturer's_code",
                          "name": "Manufacturer's Code",
                          "value": "JKFSDKJ"
                        },
                        {
                          "dataType": {
                            "name": "StaticFile",
                            "subType": null
                          },
                          "key": "manufacturer's_specification",
                          "name": "Manufacturer's Specification",
                          "value": null
                        },
                        {
                          "dataType": {
                            "name": "StaticFile",
                            "subType": null
                          },
                          "key": "material_safety_data_sheet",
                          "name": "Material Safety Data Sheet",
                          "value": null
                        },
                        {
                          "dataType": {
                            "name": "StaticFile",
                            "subType": null
                          },
                          "key": "technical_drawing",
                          "name": "Technical Drawing",
                          "value": null
                        },
                        {
                          "dataType": {
                            "name": "StaticFile",
                            "subType": null
                          },
                          "key": "3d_model",
                          "name": "3D Model",
                          "value": null
                        },
                        {
                          "dataType": {
                            "name": "MasterData",
                            "subType": "590c5a94c40d554e2c3c53fc"
                          },
                          "key": "country_of_manufacture",
                          "name": "Country of Manufacture",
                          "value": "India"
                        },
                        {
                          "dataType": {
                            "name": "Int",
                            "subType": null
                          },
                          "key": "warranty_period_in_years",
                          "name": "Warranty Period in Years",
                          "value": 4848
                        },
                        {
                          "dataType": {
                            "name": "MasterData",
                            "subType": "590c5a94c40d554e2c3c53fb"
                          },
                          "key": "status",
                          "name": "Status",
                          "value": "Under Development"
                        },
                        {
                          "dataType": {
                            "name": "String",
                            "subType": null
                          },
                          "key": "approved_vendors",
                          "name": "Approved Vendors",
                          "value": null
                        },
                        {
                          "dataType": {
                            "name": "Int",
                            "subType": null
                          },
                          "key": "shelf_life_in_days",
                          "name": "Shelf Life in Days",
                          "value": null
                        },
                        {
                          "dataType": {
                            "name": "String",
                            "subType": null
                          },
                          "key": "packing_list",
                          "name": "Packing List",
                          "value": null
                        }
                      ]
                    }
                  ]
                },
                {
                  "dataType": {
                    "name": "Array",
                    "subType": {
                      "name": "String",
                      "subType": null
                    }
                  },
                  "key": "approved_vendors",
                  "name": "Approved Vendors",
                  "value": null
                }
              ],
              "key": "purchase",
              "name": "Purchase"
            },
            {
              "columns": [
                {
                  "dataType": {
                    "name": "Int",
                    "subType": null
                  },
                  "key": "po_lead_time_in_days",
                  "name": "PO Lead Time in Days",
                  "value": null
                },
                {
                  "dataType": {
                    "name": "Int",
                    "subType": null
                  },
                  "key": "delivery_lead_time_in_days",
                  "name": "Delivery Lead Time in Days",
                  "value": null
                },
                {
                  "dataType": {
                    "name": "Int",
                    "subType": null
                  },
                  "key": "minimum_order_quantity",
                  "name": "Minimum Order Quantity",
                  "value": null
                },
                {
                  "dataType": {
                    "name": "Boolean",
                    "subType": null
                  },
                  "key": "maintain_lot",
                  "name": "Maintain Lot",
                  "value": true
                }
              ],
              "key": "planning",
              "name": "Planning"
            },
            {
              "columns": [
                {
                  "dataType": {
                    "name": "String",
                    "subType": null
                  },
                  "key": "governing_standard",
                  "name": "Governing Standard",
                  "value": "-- NA --"
                },
                {
                  "dataType": {
                    "name": "StaticFile",
                    "subType": null
                  },
                  "key": "storage_method",
                  "name": "Storage Method",
                  "value": null
                },
                {
                  "dataType": {
                    "name": "CheckList",
                    "subType": null
                  },
                  "key": "inspection_checklist",
                  "name": "Inspection Checklist",
                  "value": null
                },
                {
                  "dataType": {
                    "name": "StaticFile",
                    "subType": null
                  },
                  "key": "sampling_method",
                  "name": "Sampling Method",
                  "value": null
                }
              ],
              "key": "quality",
              "name": "Quality"
            },
            {
              "columns": [
                {
                  "dataType": {
                    "name": "Autogenerated",
                    "subType": "Date Created"
                  },
                  "key": "date_created",
                  "name": "Date Created",
                  "value": "2017-06-22T04:51:19.274Z"
                },
                {
                  "dataType": {
                    "name": "Autogenerated",
                    "subType": "Created By"
                  },
                  "key": "created_by",
                  "name": "Created By",
                  "value": "TE"
                },
                {
                  "dataType": {
                    "name": "Autogenerated",
                    "subType": "Date Last Amended"
                  },
                  "key": "date_last_amended",
                  "name": "Date Last Amended",
                  "value": "2017-06-27T05:26:57.525Z"
                },
                {
                  "dataType": {
                    "name": "Autogenerated",
                    "subType": "Last Amended By"
                  },
                  "key": "last_amended_by",
                  "name": "Last Amended By",
                  "value": "TE"
                }
              ],
              "key": "system_logs",
              "name": "System Logs"
            },
            {
              "columns": [
                {
                  "dataType": {
                    "name": "CheckList",
                    "subType": null
                  },
                  "key": "specification_sheet",
                  "name": "Specification Sheet",
                  "value": null
                },
                {
                  "dataType": {
                    "name": "String",
                    "subType": null
                  },
                  "key": "grade",
                  "name": "Grade",
                  "value": null
                },
                {
                  "dataType": {
                    "name": "Unit",
                    "subType": "mm"
                  },
                  "key": "length",
                  "name": "Length",
                  "value": {
                    "type": "mm",
                    "value": 1828.8
                  }
                },
                {
                  "dataType": {
                    "name": "Unit",
                    "subType": "mm"
                  },
                  "key": "width",
                  "name": "Width",
                  "value": null
                },
                {
                  "dataType": {
                    "name": "Unit",
                    "subType": "mm"
                  },
                  "key": "height",
                  "name": "Height",
                  "value": null
                },
                {
                  "dataType": {
                    "name": "Unit",
                    "subType": "mm"
                  },
                  "key": "thickness",
                  "name": "Thickness",
                  "value": "-- NA --"
                },
                {
                  "dataType": {
                    "name": "String",
                    "subType": null
                  },
                  "key": "method",
                  "name": "Method",
                  "value": "-- NA --"
                },
                {
                  "dataType": {
                    "name": "String",
                    "subType": null
                  },
                  "key": "temper_designation",
                  "name": "Temper Designation",
                  "value": "-- NA --"
                },
                {
                  "dataType": {
                    "name": "String",
                    "subType": null
                  },
                  "key": "finish",
                  "name": "Finish",
                  "value": null
                },
                {
                  "dataType": {
                    "name": "Unit",
                    "subType": "kg/m²"
                  },
                  "key": "weight/unit_area",
                  "name": "Weight/Unit Area",
                  "value": null
                },
                {
                  "dataType": {
                    "name": "Unit",
                    "subType": "kg/m"
                  },
                  "key": "weight/unit_length",
                  "name": "Weight/Unit Length",
                  "value": null
                },
                {
                  "dataType": {
                    "name": "String",
                    "subType": null
                  },
                  "key": "additional_features",
                  "name": "Additional Features",
                  "value": null
                }
              ],
              "key": "specifications",
              "name": "Specifications"
            }
          ],
          "group": "Aluminium and Copper",
          "id": "ALM000047"
        }
      ],
      selectedTab: "classification",
      onTabChange: sinon.spy(),
    };
    wrapper = shallow(<PageTab {...props}/>);
  });
  it("should render tab and tab panels", () => {
    expect(wrapper).to.have.descendants('Tabs');
    expect(wrapper.find('Tabs')).to.have.prop('selectedIndex', 0);
    expect(wrapper.find('Tabs').children()).to.have.descendants('TabList');
    expect(wrapper.find('Tabs').children().find('TabList').children()).to.have.descendants('Tab');
    expect(wrapper.find('Tabs').children()).to.have.descendants('TabPanel');
  });


  it('should call onTabChange with header name when Tabs onSelect is called', () => {
    wrapper.find('Tabs').simulate('select', 0);
    expect(props.onTabChange).to.have.been.calledWith('classification');
  });
});

describe("Page Tab with service data", () => {
  let props, wrapper, onCurrentHeaderChange;
  beforeEach(() => {
    onCurrentHeaderChange = sinon.spy();
    props = {
      componentType: "service",
      values: [
        {
          "id": "FDP1026",
          "group": "FLOORING | DADO | PAVIOUR",
          "headers": [
            {
              "columns": [
                {
                  "dataType": {
                    "name": "Constant",
                    "subType": "FLOORING | DADO | PAVIOUR"
                  },
                  "key": "service_level_1",
                  "name": "Service Level 1",
                  "value": "FLOORING | DADO | PAVIOUR"
                },
                {
                  "dataType": {
                    "name": "MasterData",
                    "subType": "590c5a94c40d554e2c3c5403"
                  },
                  "key": "service_level_2",
                  "name": "Service Level 2",
                  "value": "Flooring"
                },
                {
                  "dataType": {
                    "name": "MasterData",
                    "subType": "590c5a94c40d554e2c3c5404"
                  },
                  "key": "service_level_3",
                  "name": "Service Level 3",
                  "value": "Natural Stone"
                },
                {
                  "dataType": {
                    "name": "MasterData",
                    "subType": "590c5a94c40d554e2c3c5405"
                  },
                  "key": "service_level_4",
                  "name": "Service Level 4",
                  "value": "Italian Marble"
                },
                {
                  "dataType": {
                    "name": "MasterData",
                    "subType": "590c5a94c40d554e2c3c5406"
                  },
                  "key": "service_level_5",
                  "name": "Service Level 5",
                  "value": null
                },
                {
                  "dataType": {
                    "name": "MasterData",
                    "subType": "590c5a94c40d554e2c3c5407"
                  },
                  "key": "service_level_6",
                  "name": "Service Level 6",
                  "value": null
                },
                {
                  "dataType": {
                    "name": "MasterData",
                    "subType": "590c5a94c40d554e2c3c5408"
                  },
                  "key": "service_level_7",
                  "name": "Service Level 7",
                  "value": null
                }
              ],
              "key": "classification",
              "name": "Classification"
            },
            {
              "columns": [
                {
                  "dataType": {
                    "name": "Autogenerated",
                    "subType": "Service Code"
                  },
                  "key": "service_code",
                  "name": "Service Code",
                  "value": "FDP1026"
                },
                {
                  "dataType": {
                    "name": "String",
                    "subType": null
                  },
                  "key": "wbs_code",
                  "name": "WBS Code",
                  "value": "SATTAR"
                },
                {
                  "dataType": {
                    "name": "String",
                    "subType": null
                  },
                  "key": "short_description",
                  "name": "Short Description",
                  "value": "Short Description"
                },
                {
                  "dataType": {
                    "name": "String",
                    "subType": null
                  },
                  "key": "unit_of_measure",
                  "name": "Unit of Measure",
                  "value": "m2"
                },
                {
                  "dataType": {
                    "name": "String",
                    "subType": null
                  },
                  "key": "hsn_code",
                  "name": "HSN Code",
                  "value": null
                },
                {
                  "dataType": {
                    "name": "MasterData",
                    "subType": "590c5a94c40d554e2c3c53fb"
                  },
                  "key": "service_status",
                  "name": "Service Status",
                  "value": "Approved"
                }
              ],
              "key": "general",
              "name": "General"
            },
            {
              "columns": [
                {
                  "dataType": {
                    "name": "StaticFile",
                    "subType": null
                  },
                  "key": "method_of_measurement",
                  "name": "Method of Measurement",
                  "value": null
                },
                {
                  "dataType": {
                    "name": "CheckList",
                    "subType": null
                  },
                  "key": "general_so_terms_&_conditions",
                  "name": "General SO Terms & Conditions",
                  "value": null
                },
                {
                  "dataType": {
                    "name": "CheckList",
                    "subType": null
                  },
                  "key": "special_so_terms_&_conditions",
                  "name": "Special SO Terms & Conditions",
                  "value": null
                },
                {
                  "dataType": {
                    "name": "Money",
                    "subType": null
                  },
                  "key": "last_purchase_rate",
                  "name": "Last Purchase Rate",
                  "value": null
                },
                {
                  "dataType": {
                    "name": "Money",
                    "subType": null
                  },
                  "key": "weighted_average_purchase_rate",
                  "name": "Weighted Average Purchase Rate",
                  "value": null
                },
                {
                  "dataType": {
                    "name": "Unit",
                    "subType": "%"
                  },
                  "key": "procurement_rate_threshold_%",
                  "name": "Procurement Rate Threshold %",
                  "value": null
                },
                {
                  "dataType": {
                    "name": "Array",
                    "subType": {
                      "name": "String",
                      "subType": null
                    }
                  },
                  "key": "approved_vendors",
                  "name": "Approved Vendors",
                  "value": null
                }
              ],
              "key": "purchase",
              "name": "Purchase"
            },
            {
              "columns": [
                {
                  "dataType": {
                    "name": "Int",
                    "subType": null
                  },
                  "key": "so_lead_time_in_days",
                  "name": "SO Lead Time in Days",
                  "value": null
                },
                {
                  "dataType": {
                    "name": "Int",
                    "subType": null
                  },
                  "key": "vendor_mobilisation_time_in_days",
                  "name": "Vendor Mobilisation Time in Days",
                  "value": null
                },
                {
                  "dataType": {
                    "name": "Int",
                    "subType": null
                  },
                  "key": "minimum_order_quantity",
                  "name": "Minimum Order Quantity",
                  "value": null
                }
              ],
              "key": "planning",
              "name": "Planning"
            },
            {
              "columns": [
                {
                  "dataType": {
                    "name": "Array",
                    "subType": {
                      "name": "String",
                      "subType": null
                    }
                  },
                  "key": "governing_standard",
                  "name": "Governing Standard",
                  "value": null
                },
                {
                  "dataType": {
                    "name": "CheckList",
                    "subType": null
                  },
                  "key": "quality_checklist",
                  "name": "Quality Checklist",
                  "value": null
                },
                {
                  "dataType": {
                    "name": "StaticFile",
                    "subType": null
                  },
                  "key": "safety_requirements",
                  "name": "Safety Requirements",
                  "value": null
                }
              ],
              "key": "quality",
              "name": "Quality"
            },
            {
              "columns": [
                {
                  "dataType": {
                    "name": "Autogenerated",
                    "subType": "Date Created"
                  },
                  "key": "date_created",
                  "name": "Date Created",
                  "value": "2017-05-17T09:08:22.254Z"
                },
                {
                  "dataType": {
                    "name": "Autogenerated",
                    "subType": "Created By"
                  },
                  "key": "created_by",
                  "name": "Created By",
                  "value": "TE"
                },
                {
                  "dataType": {
                    "name": "Autogenerated",
                    "subType": "Date Last Amended"
                  },
                  "key": "date_last_amended",
                  "name": "Date Last Amended",
                  "value": "2017-05-17T09:08:22.254Z"
                },
                {
                  "dataType": {
                    "name": "Autogenerated",
                    "subType": "Last Amended By"
                  },
                  "key": "last_amended_by",
                  "name": "Last Amended By",
                  "value": "TE"
                }
              ],
              "key": "system_logs",
              "name": "System Logs"
            }
          ]
        },
        {
          "id": "FDP2003",
          "group": "FLOORING | DADO | PAVIOUR",
          "headers": [
            {
              "columns": [
                {
                  "dataType": {
                    "name": "Constant",
                    "subType": "FLOORING | DADO | PAVIOUR"
                  },
                  "key": "service_level_1",
                  "name": "Service Level 1",
                  "value": "FLOORING | DADO | PAVIOUR"
                },
                {
                  "dataType": {
                    "name": "MasterData",
                    "subType": "590c5a94c40d554e2c3c5403"
                  },
                  "key": "service_level_2",
                  "name": "Service Level 2",
                  "value": "Flooring"
                },
                {
                  "dataType": {
                    "name": "MasterData",
                    "subType": "590c5a94c40d554e2c3c5404"
                  },
                  "key": "service_level_3",
                  "name": "Service Level 3",
                  "value": "Natural Stone"
                },
                {
                  "dataType": {
                    "name": "MasterData",
                    "subType": "590c5a94c40d554e2c3c5405"
                  },
                  "key": "service_level_4",
                  "name": "Service Level 4",
                  "value": "Italian Marble"
                },
                {
                  "dataType": {
                    "name": "MasterData",
                    "subType": "590c5a94c40d554e2c3c5406"
                  },
                  "key": "service_level_5",
                  "name": "Service Level 5",
                  "value": null
                },
                {
                  "dataType": {
                    "name": "MasterData",
                    "subType": "590c5a94c40d554e2c3c5407"
                  },
                  "key": "service_level_6",
                  "name": "Service Level 6",
                  "value": null
                },
                {
                  "dataType": {
                    "name": "MasterData",
                    "subType": "590c5a94c40d554e2c3c5408"
                  },
                  "key": "service_level_7",
                  "name": "Service Level 7",
                  "value": null
                }
              ],
              "key": "classification",
              "name": "Classification"
            },
            {
              "columns": [
                {
                  "dataType": {
                    "name": "Autogenerated",
                    "subType": "Service Code"
                  },
                  "key": "service_code",
                  "name": "Service Code",
                  "value": "FDP2003"
                },
                {
                  "dataType": {
                    "name": "String",
                    "subType": null
                  },
                  "key": "wbs_code",
                  "name": "WBS Code",
                  "value": "SATTAR"
                },
                {
                  "dataType": {
                    "name": "String",
                    "subType": null
                  },
                  "key": "short_description",
                  "name": "Short Description",
                  "value": "Short Description"
                },
                {
                  "dataType": {
                    "name": "String",
                    "subType": null
                  },
                  "key": "unit_of_measure",
                  "name": "Unit of Measure",
                  "value": "m2"
                },
                {
                  "dataType": {
                    "name": "String",
                    "subType": null
                  },
                  "key": "hsn_code",
                  "name": "HSN Code",
                  "value": null
                },
                {
                  "dataType": {
                    "name": "MasterData",
                    "subType": "590c5a94c40d554e2c3c53fb"
                  },
                  "key": "service_status",
                  "name": "Service Status",
                  "value": "Approved"
                }
              ],
              "key": "general",
              "name": "General"
            },
            {
              "columns": [
                {
                  "dataType": {
                    "name": "StaticFile",
                    "subType": null
                  },
                  "key": "method_of_measurement",
                  "name": "Method of Measurement",
                  "value": null
                },
                {
                  "dataType": {
                    "name": "CheckList",
                    "subType": null
                  },
                  "key": "general_so_terms_&_conditions",
                  "name": "General SO Terms & Conditions",
                  "value": null
                },
                {
                  "dataType": {
                    "name": "CheckList",
                    "subType": null
                  },
                  "key": "special_so_terms_&_conditions",
                  "name": "Special SO Terms & Conditions",
                  "value": null
                },
                {
                  "dataType": {
                    "name": "Money",
                    "subType": null
                  },
                  "key": "last_purchase_rate",
                  "name": "Last Purchase Rate",
                  "value": null
                },
                {
                  "dataType": {
                    "name": "Money",
                    "subType": null
                  },
                  "key": "weighted_average_purchase_rate",
                  "name": "Weighted Average Purchase Rate",
                  "value": null
                },
                {
                  "dataType": {
                    "name": "Unit",
                    "subType": "%"
                  },
                  "key": "procurement_rate_threshold_%",
                  "name": "Procurement Rate Threshold %",
                  "value": null
                },
                {
                  "dataType": {
                    "name": "Array",
                    "subType": {
                      "name": "String",
                      "subType": null
                    }
                  },
                  "key": "approved_vendors",
                  "name": "Approved Vendors",
                  "value": null
                }
              ],
              "key": "purchase",
              "name": "Purchase"
            },
            {
              "columns": [
                {
                  "dataType": {
                    "name": "Int",
                    "subType": null
                  },
                  "key": "so_lead_time_in_days",
                  "name": "SO Lead Time in Days",
                  "value": null
                },
                {
                  "dataType": {
                    "name": "Int",
                    "subType": null
                  },
                  "key": "vendor_mobilisation_time_in_days",
                  "name": "Vendor Mobilisation Time in Days",
                  "value": null
                },
                {
                  "dataType": {
                    "name": "Int",
                    "subType": null
                  },
                  "key": "minimum_order_quantity",
                  "name": "Minimum Order Quantity",
                  "value": null
                }
              ],
              "key": "planning",
              "name": "Planning"
            },
            {
              "columns": [
                {
                  "dataType": {
                    "name": "Array",
                    "subType": {
                      "name": "String",
                      "subType": null
                    }
                  },
                  "key": "governing_standard",
                  "name": "Governing Standard",
                  "value": null
                },
                {
                  "dataType": {
                    "name": "CheckList",
                    "subType": null
                  },
                  "key": "quality_checklist",
                  "name": "Quality Checklist",
                  "value": null
                },
                {
                  "dataType": {
                    "name": "StaticFile",
                    "subType": null
                  },
                  "key": "safety_requirements",
                  "name": "Safety Requirements",
                  "value": null
                }
              ],
              "key": "quality",
              "name": "Quality"
            },
            {
              "columns": [
                {
                  "dataType": {
                    "name": "Autogenerated",
                    "subType": "Date Created"
                  },
                  "key": "date_created",
                  "name": "Date Created",
                  "value": "2017-06-27T11:50:28.052Z"
                },
                {
                  "dataType": {
                    "name": "Autogenerated",
                    "subType": "Created By"
                  },
                  "key": "created_by",
                  "name": "Created By",
                  "value": "TE"
                },
                {
                  "dataType": {
                    "name": "Autogenerated",
                    "subType": "Date Last Amended"
                  },
                  "key": "date_last_amended",
                  "name": "Date Last Amended",
                  "value": "2017-06-27T11:50:28.052Z"
                },
                {
                  "dataType": {
                    "name": "Autogenerated",
                    "subType": "Last Amended By"
                  },
                  "key": "last_amended_by",
                  "name": "Last Amended By",
                  "value": "TE"
                }
              ],
              "key": "system_logs",
              "name": "System Logs"
            }
          ]
        }
      ]
    };
    wrapper = shallow(<PageTab {...props}/>);
  });
  it("should render tab and tab panels", () => {
    expect(wrapper).to.have.descendants('Tabs');
    expect(wrapper.find('Tabs').children()).to.have.descendants('TabList');
    expect(wrapper.find('Tabs').children().find('TabList').children()).to.have.descendants('Tab');
    expect(wrapper.find('Tabs').children()).to.have.descendants('TabPanel');
  });
});
