//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TE.ComponentLibrary.ComponentLibrary.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.0.1.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://180.151.39.226:50100/XISOAPAdapter/MessageServlet?senderParty=&senderServi" +
            "ce=BS_FUGUE_QAS&receiverParty=&receiverService=&interface=MaterialMaster_Out&int" +
            "erfaceNamespace=http%3A%2F%2Ftotal-environment%2FPI%2FMaterialMaster")]
        public string ComponentLibrary_SAPServiceReference_MaterialMaster_OutService {
            get {
                return ((string)(this["ComponentLibrary_SAPServiceReference_MaterialMaster_OutService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://180.151.39.226:50100/XISOAPAdapter/MessageServlet?senderParty=&senderServi" +
            "ce=BS_FUGUE_QAS&receiverParty=&receiverService=&interface=ServiceMaster_Out&inte" +
            "rfaceNamespace=http%3A%2F%2Ftotal-environment%2FPI%2FServiceMaster")]
        public string ComponentLibrary_ServiceSAPServiceReference_ServiceMaster_OutService {
            get {
                return ((string)(this["ComponentLibrary_ServiceSAPServiceReference_ServiceMaster_OutService"]));
            }
        }
    }
}
